services:
  - type: worker
    name: whale_signal_bot
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: COINGLASS_API_KEY
        sync: false
