services:
  - type: web
    name: telegram-signal-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false   # مقدار رو خودت دستی توی داشبورد Render وارد کن
      - key: DB_URL
        sync: false   # آدرس Postgres از Render
      - key: RENDER_EXTERNAL_URL
        value: https://telegram-signal-bot.onrender.com   # بعد از ساخت سرویس، دامنه رو جایگزین کن
    plan: free
